[book]
authors = ["dwx"]
language = "zh-CN"
src = "."
title = "Java 高级开发工程师技术解析文档"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/dwx/AiDocs"
preferred-dark-theme = "navy"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 0
