import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Create separate sidebars for each main category
  javaSidebar: [{type: 'autogenerated', dirName: 'java'}],
  databaseSidebar: [{type: 'autogenerated', dirName: 'database'}],
  cacheSidebar: [{type: 'autogenerated', dirName: 'cache'}],
  distributedSidebar: [{type: 'autogenerated', dirName: 'distributed'}],
  rustSidebar: [{type: 'autogenerated', dirName: 'rust'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  javaSidebar: [
    {
      type: 'category',
      label: 'Spring Framework',
      items: [
        {
          type: 'autogenerated',
          dirName: 'java/spring',
        },
        {
          type: 'autogenerated',
          dirName: 'java/spring/ioc-aop.md',
        },
        {
          type: 'autogenerated',
          dirName: 'java/spring/spring-context-refresh.md',
        },
        {
          type: 'autogenerated',
          dirName: 'java/spring/springmvc-principles.md',
        },
        {
          type: 'autogenerated',
          dirName: 'java/spring/springmvc-advanced.md',
        },
        {
          type: 'autogenerated',
          dirName: 'java/spring/transaction.md',
        },
        {
          type: 'autogenerated',
          dirName: 'java/spring/springboot-internals.md',
        },
        {
          type: 'autogenerated',
          dirName: 'java/spring/springboot-fatjar.md',
        },
        {
          type: 'autogenerated',
          dirName: 'java/spring/springboot-extension.md',
        },
        {
          type: 'autogenerated',
          dirName: 'java/spring/beandefinition-internals.md',
        },
      ],
    },
  ],
};

export default sidebars;
