import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Create separate sidebars for each main category
  javaSidebar: [
    {
      type: 'category',
      label: 'Java Core',
      items: [
        {
          type: 'autogenerated',
          dirName: 'java',
        },
      ],
    }
  ],
  databaseSidebar: [{type: 'autogenerated', dirName: 'database'}],
  cacheSidebar: [{type: 'autogenerated', dirName: 'cache'}],
  distributedSidebar: [{type: 'autogenerated', dirName: 'distributed'}],
  rustSidebar: [
  "rust/title-page",
  "rust/foreword",
  "rust/ch00-00-introduction",
  {
    "type": "category",
    "label": "入门指南",
    "link": {
      "type": "doc",
      "id": "rust/ch01-00-getting-started"
    },
    "items": [
      "rust/ch01-01-installation",
      "rust/ch01-02-hello-world",
      "rust/ch01-03-hello-cargo"
    ]
  },
  {
    "type": "category",
    "label": "猜数字游戏",
    "link": {
      "type": "doc",
      "id": "rust/ch02-00-guessing-game-tutorial"
    },
    "items": []
  },
  {
    "type": "category",
    "label": "通用编程概念",
    "link": {
      "type": "doc",
      "id": "rust/ch03-00-common-programming-concepts"
    },
    "items": [
      "rust/ch03-01-variables-and-mutability",
      "rust/ch03-02-data-types",
      "rust/ch03-03-how-functions-work",
      "rust/ch03-04-comments",
      "rust/ch03-05-control-flow"
    ]
  },
  {
    "type": "category",
    "label": "认识所有权",
    "link": {
      "type": "doc",
      "id": "rust/ch04-00-understanding-ownership"
    },
    "items": [
      "rust/ch04-01-what-is-ownership",
      "rust/ch04-02-references-and-borrowing",
      "rust/ch04-03-slices"
    ]
  },
  {
    "type": "category",
    "label": "使用结构体组织关联数据",
    "link": {
      "type": "doc",
      "id": "rust/ch05-00-structs"
    },
    "items": [
      "rust/ch05-01-defining-structs",
      "rust/ch05-02-example-structs",
      "rust/ch05-03-method-syntax"
    ]
  },
  {
    "type": "category",
    "label": "枚举和模式匹配",
    "link": {
      "type": "doc",
      "id": "rust/ch06-00-enums"
    },
    "items": [
      "rust/ch06-01-defining-an-enum",
      "rust/ch06-02-match",
      "rust/ch06-03-if-let"
    ]
  },
  {
    "type": "category",
    "label": "使用包、Crate 和模块管理不断增长的项目",
    "link": {
      "type": "doc",
      "id": "rust/ch07-00-managing-growing-projects-with-packages-crates-and-modules"
    },
    "items": [
      "rust/ch07-01-packages-and-crates",
      "rust/ch07-02-defining-modules-to-control-scope-and-privacy",
      "rust/ch07-03-paths-for-referring-to-an-item-in-the-module-tree",
      "rust/ch07-04-bringing-paths-into-scope-with-the-use-keyword",
      "rust/ch07-05-separating-modules-into-different-files"
    ]
  },
  {
    "type": "category",
    "label": "常见集合",
    "link": {
      "type": "doc",
      "id": "rust/ch08-00-common-collections"
    },
    "items": [
      "rust/ch08-01-vectors",
      "rust/ch08-02-strings",
      "rust/ch08-03-hash-maps"
    ]
  },
  {
    "type": "category",
    "label": "错误处理",
    "link": {
      "type": "doc",
      "id": "rust/ch09-00-error-handling"
    },
    "items": [
      "rust/ch09-01-unrecoverable-errors-with-panic",
      "rust/ch09-02-recoverable-errors-with-result",
      "rust/ch09-03-to-panic-or-not-to-panic"
    ]
  },
  {
    "type": "category",
    "label": "泛型、trait 与生命周期",
    "link": {
      "type": "doc",
      "id": "rust/ch10-00-generics"
    },
    "items": [
      "rust/ch10-01-syntax",
      "rust/ch10-02-traits",
      "rust/ch10-03-lifetime-syntax"
    ]
  },
  {
    "type": "category",
    "label": "编写自动化测试",
    "link": {
      "type": "doc",
      "id": "rust/ch11-00-testing"
    },
    "items": [
      "rust/ch11-01-writing-tests",
      "rust/ch11-02-running-tests",
      "rust/ch11-03-test-organization"
    ]
  },
  {
    "type": "category",
    "label": "一个 I/O 项目：构建命令行程序",
    "link": {
      "type": "doc",
      "id": "rust/ch12-00-an-io-project"
    },
    "items": [
      "rust/ch12-01-accepting-command-line-arguments",
      "rust/ch12-02-reading-a-file",
      "rust/ch12-03-improving-error-handling-and-modularity",
      "rust/ch12-04-testing-the-librarys-functionality",
      "rust/ch12-05-working-with-environment-variables",
      "rust/ch12-06-writing-to-stderr-instead-of-stdout"
    ]
  },
  {
    "type": "category",
    "label": "Rust 中的函数式语言功能：迭代器与闭包",
    "link": {
      "type": "doc",
      "id": "rust/ch13-00-functional-features"
    },
    "items": [
      "rust/ch13-01-closures",
      "rust/ch13-02-iterators",
      "rust/ch13-03-improving-our-io-project",
      "rust/ch13-04-performance"
    ]
  },
  {
    "type": "category",
    "label": "更多关于 Cargo 和 Crates.io 的内容",
    "link": {
      "type": "doc",
      "id": "rust/ch14-00-more-about-cargo"
    },
    "items": [
      "rust/ch14-01-release-profiles",
      "rust/ch14-02-publishing-to-crates-io",
      "rust/ch14-03-cargo-workspaces",
      "rust/ch14-04-installing-binaries",
      "rust/ch14-05-extending-cargo"
    ]
  },
  {
    "type": "category",
    "label": "智能指针",
    "link": {
      "type": "doc",
      "id": "rust/ch15-00-smart-pointers"
    },
    "items": [
      "rust/ch15-01-box",
      "rust/ch15-02-deref",
      "rust/ch15-03-drop",
      "rust/ch15-04-rc",
      "rust/ch15-05-interior-mutability",
      "rust/ch15-06-reference-cycles"
    ]
  },
  {
    "type": "category",
    "label": "无畏并发",
    "link": {
      "type": "doc",
      "id": "rust/ch16-00-concurrency"
    },
    "items": [
      "rust/ch16-01-threads",
      "rust/ch16-02-message-passing",
      "rust/ch16-03-shared-state",
      "rust/ch16-04-extensible-concurrency-sync-and-send"
    ]
  },
  {
    "type": "category",
    "label": "Rust 的面向对象编程特性",
    "link": {
      "type": "doc",
      "id": "rust/ch17-00-oop"
    },
    "items": [
      "rust/ch17-01-what-is-oo",
      "rust/ch17-02-trait-objects",
      "rust/ch17-03-oo-design-patterns"
    ]
  },
  {
    "type": "category",
    "label": "模式和匹配",
    "link": {
      "type": "doc",
      "id": "rust/ch18-00-patterns"
    },
    "items": [
      "rust/ch18-01-all-the-places-for-patterns",
      "rust/ch18-02-refutability",
      "rust/ch18-03-pattern-syntax"
    ]
  },
  {
    "type": "category",
    "label": "高级特征",
    "link": {
      "type": "doc",
      "id": "rust/ch19-00-advanced-features"
    },
    "items": [
      "rust/ch19-01-unsafe-rust",
      "rust/ch19-03-advanced-traits",
      "rust/ch19-04-advanced-types",
      "rust/ch19-05-advanced-functions-and-closures",
      "rust/ch19-06-macros"
    ]
  },
  {
    "type": "category",
    "label": "最后的项目: 构建多线程 Web 服务器",
    "link": {
      "type": "doc",
      "id": "rust/ch20-00-final-project-a-web-server"
    },
    "items": [
      "rust/ch20-01-single-threaded",
      "rust/ch20-02-multithreaded",
      "rust/ch20-03-graceful-shutdown-and-cleanup"
    ]
  },
  {
    "type": "category",
    "label": "附录",
    "link": {
      "type": "doc",
      "id": "rust/appendix-00"
    },
    "items": [
      "rust/appendix-01-keywords",
      "rust/appendix-02-operators",
      "rust/appendix-03-derivable-traits",
      "rust/appendix-04-useful-development-tools",
      "rust/appendix-05-editions",
      "rust/appendix-06-translation",
      "rust/appendix-07-nightly-rust"
    ]
  }
],
  reactSidebar: [{type: 'autogenerated', dirName: 'react'}],
  webBasicsSidebar: [{type: 'autogenerated', dirName: 'web-basics'}],
  homeSidebar: [
    'intro'
  ],
  interviewSidebar: [{type: 'autogenerated', dirName: 'interview'}]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],*/
};

export default sidebars;
